name: Release

on:
  push:
    tags:
    - 'v*'

env:
  TZ: Asia/Shanghai
  GO_VERSION: '1.20'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: install task
      run: |
        echo "install task"
        go install github.com/go-task/task/v3/cmd/task@latest
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Publish .deb & .rpm to Gemfury
      env:
        FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      run: |
        for filename in dist/*.deb; do
          echo "Pushing $filename to apt repository"
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/ysicing/
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/ysicing/
        done
        for filename in dist/*.rpm; do
          echo "Pushing $filename to rpm repository"
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/ysicing/
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/ysicing/
        done
    - name: Build docs
      run: |
        task godoc
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs
    - run: git fetch --prune --prune-tags
    - run: git tag -l 'v*'
    - run: ./hack/scripts/changelog.sh > CHANGELOG.md
    - run: ./hack/scripts/gentap.sh
    - uses: peter-evans/create-pull-request@v5
      with:
        title: 'docs: updated CHANGELOG.md & docs'
        commit-message: 'docs: updated CHANGELOG.md & docs'
        branch: create-pull-request/changelog
        signoff: true
        delete-branch: true
        assignees: ysicing
        reviewers: ysicing
        labels: |
          kind/doc
          kind/bot
